{% set name = "autogluon" %}
{% set version = "0.3.1" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/awslabs/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 42152eafbbfa04c2c8b002fe37a3b82a915db6aa1d76859c0220c238a4759ede

build:
  number: 0
  noarch: python

outputs:
  - name: {{ name }}-core
    script: install_core.sh
    requirements:
      host:
        - pip
        - python
        - wheel
        - setuptools
      run:
        - python
        - numpy
        - scipy <1.7 # not in setup but pip check complains
        - scikit-learn
        - pandas
        - tqdm
        - python-graphviz
        - cython
        - configspace 0.4.19
        - tornado >=5.0.1
        - requests
        - matplotlib
        - paramiko >=2.4
        - dask >=2.6.0
        - distributed >=2.6.0
        - boto3
        - autograd >=1.3
        - dill >=0.3.3,<1.0
    test:
      requires:
        - pip
        - pytest
      imports:
        - autogluon.core
      commands:
        - pip check
        - cd core && pytest

  - name: {{ name }}-features
    script: install_features.sh
    requirements:
      host:
        - pip
        - python
        - wheel
        - setuptools
      run:
        - {{ pin_subpackage(name + '-core') }}
    test:
      requires:
        - pip
        - pytest
      imports:
        - autogluon.features
      commands:
        - pip check
        - cd features && pytest

  - name: {{ name }}-tabular
    script: install_tabular.sh
    requirements:
      host:
        - pip
        - python
        - wheel
        - setuptools
      run:
        - {{ pin_subpackage(name + '-core') }}
        - {{ pin_subpackage(name + '-features') }}
        - psutil >=5.7.3,<5.9
        - networkx >=2.3,<3.0
    test:
      requires:
        - pip
        - pytest
      imports:
        - autogluon.tabular
      commands:
        - pip check
        - cd tabular && pytest

  - name: {{ name }}-mxnet
    script: install_mxnet.sh
    requirements:
      host:
        - pip
        - python
        - wheel
        - setuptools
      run:
        - {{ pin_subpackage(name + '-core') }}
        - mxnet
        - pillow
    test:
      requires:
        - pip
        - pytest
        - openml
      imports:
        - autogluon.mxnet
      commands:
        - pip check
        - cd mxnet && pytest

#  - name: {{ name }}-extra
#    script: install_extra.sh
#    requirements:
#      host:
#        - pip
#        - python
#        - wheel
#        - setuptools
#      run:
#        - {{ pin_subpackage(name + '-core'}}
#        - python
#        - numpy
#        - scipy <1.7
#        - pandas
#        - scikit-learn
#        - gluoncv
#        - python-graphviz
#        - autograd >=1.3
#    test:
#      requires:
#        - pip
#        - pytest
#      imports:
#        - autogluon.extra
#      commands:
#        - pip check
#        - cd extra && pytest

about:
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    AutoGluon automates machine learning tasks enabling you to easily achieve
    strong predictive performance in your applications.

extra:
  recipe-maintainers:
    - dkomisar

